POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "yalla@gmail.com",
    "password": "65346364363"
}

###
POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
     "email": "yesSir@gmail.com",
    "password": "65346364363"
}
###
POST http://localhost:3000/api/stripe/checkout